version: '2'
services:
  db:
    image: mariadb:10.5.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./sql:/usr/src/sql
      - ./sql/my.cnf:/etc/mysql/conf.d/my.cnf
  web:
    build: .
    command: 'rackup -o 0.0.0.0 -p 3000 config.ru'
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./ruby/lib:/usr/src/app/lib
    environment:
      MYSQL_HOST: db